management.metrics.enable:
    all: false
    application: true # reports startup time, useful for future comparison
    http.server.requests: true # reports http request counts
    resilience4j.circuitbreaker: true # reports circuit breaker status
    jvm.memory: true # reports heap status
    jvm.gc: true # reports garbage collector metrics, useful to detect too long pauses
    mongodb.driver: true # reports useful mongo statistics, like waiting queue

resilience4j.retry:
  instances:
    newTransaction:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: false
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
    getTransactionInfo:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: false
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
    requestTransactionAuthorization:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: false
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
        - it.pagopa.transactions.exceptions.PaymentMethodNotFoundException
        - it.pagopa.transactions.exceptions.NpgNotRetryableErrorException
        - it.pagopa.transactions.exceptions.LockNotAcquiredException
    updateTransactionAuthorization:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: false
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
        - it.pagopa.transactions.exceptions.LockNotAcquiredException
    cancelTransaction:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: false
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
    addUserReceipt:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: false
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 2
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    transactions-backend:
      baseConfig: default
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
    node-backend:
      baseConfig: default
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException
    ecommerce-db:
      baseConfig: default
      ignoreExceptions:
        - it.pagopa.transactions.exceptions.UnsatisfiablePspRequestException
        - it.pagopa.transactions.exceptions.PaymentNoticeAllCCPMismatchException
        - it.pagopa.transactions.exceptions.TransactionNotFoundException
        - it.pagopa.transactions.exceptions.AlreadyProcessedException
        - it.pagopa.transactions.exceptions.NotImplementedException
        - it.pagopa.transactions.exceptions.InvalidRequestException
        - it.pagopa.transactions.exceptions.TransactionAmountMismatchException
        - it.pagopa.transactions.exceptions.NodoErrorException
        - it.pagopa.transactions.exceptions.InvalidNodoResponseException

