parameters:
  # Required
  - name: "COLLECTION_TEST_FILE"
    type: "string"
  - name: "ENV_FILE"
    type: string
  - name: "TEST_FILE_PREFIX"
    type: string

steps:
  - script: |
      yarn global add newman
    displayName: 'Newman installation'
  - script: |
      newman run ${{ parameters.COLLECTION_TEST_FILE }} -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml
    displayName: 'Run api test app - env file: ${{ parameters.ENV_FILE }}'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'